Repository JMC-Soft/automated-scoring, pull requests merged in 2023-07, with the labels that each got.

#18 refactore : 프론트 파일 이동 및 파일명 변경
  web/src/components/EssaySection.tsx
  web/src/components/Note.tsx
  web/src/components/Sidebar.tsx
  web/src/components/StoreInitializer.tsx
  web/src/components/TopicBar.tsx
  web/src/components/ui/Accordion/Accordion.tsx
  web/src/components/ui/Accordion/AccordionTitle.tsx
  web/src/lib/constants/constants.ts
  web/src/lib/types.d.ts
  web/src/lib/utils/api/getUser.ts
  web/src/lib/utils/api/logOut.ts
  web/src/lib/utils/api/login.ts
  web/src/lib/utils/api/signUp.ts
  web/src/lib/utils/utils.ts
  web/src/store/authStore.ts
  web/src/store/subjectStore.ts
Labels: refactor

#19 Feat/save essay
  web/package.json
  web/src/app/api/config/firebase.admin.ts
  web/src/app/api/const/dataSet.ts
  web/src/app/api/lib/auth.ts
  web/src/app/api/lib/getColRef.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/essay/countEssay.ts
  web/src/app/api/repository/essay/saveEssay.ts
  web/src/app/api/repository/user/createUser.ts
  web/src/app/api/repository/user/findUserByEmail.ts
  web/src/app/api/repository/user/findUserByEmailAndPassword.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/login/route.ts
  web/src/app/api/v1/register/[email]/check/route.ts
  web/src/app/api/v1/register/route.ts
  web/src/app/api/v1/verify/idToken/route.ts
Labels: feature

#20 feat: onnx 양자화 버전 및 requirement
  python/app.py
  python/requirements.txt
  python/test
Labels: feature

#22 Feat/result page
  web/package-lock.json
  web/package.json
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/app/result/page.tsx
  web/src/components/EssaySection.tsx
  web/src/components/Note.tsx
  web/src/components/ResultSection/DetailView.tsx
  web/src/components/ResultSection/OverView.tsx
  web/src/components/ResultSection/SummaryView.tsx
  web/src/components/ResultSection/index.tsx
  web/src/components/ReviewSection.tsx
  web/src/components/TapBar.tsx
  web/src/components/TopicBar.tsx
  web/src/components/ui/Button.tsx
  web/src/components/ui/Chart/HorizontalBarChart.tsx
  web/src/components/ui/Chart/NormalDistributionGraph.tsx
  web/src/components/ui/Chart/TriangleRadarChart.tsx
  web/src/components/ui/Chart/TwiceBarChart.tsx
  web/src/lib/utils/chart/createNormalDistData.ts
Labels: feature

#23 feat: 에러 핸들링
  web/package-lock.json
  web/package.json
  web/src/app/api/config/firebase.admin.ts
  web/src/app/api/config/firebase.client.ts
  web/src/app/api/const/dataSet.ts
  web/src/app/api/lib/auth.ts
  web/src/app/api/lib/class/ApiError.ts
  web/src/app/api/lib/clientAuth.ts
  web/src/app/api/lib/getColRef.ts
  web/src/app/api/lib/getUserToken.ts
  web/src/app/api/lib/isLoggedIn.ts
  web/src/app/api/lib/scoring/calculateEssayResult.ts
  web/src/app/api/lib/scoring/calculateEssaySub.ts
  web/src/app/api/lib/scoring/calculateEssayTotal.ts
  web/src/app/api/lib/scoring/calculateGrade.ts
  web/src/app/api/lib/scoring/fetchToScoringServer.ts
  web/src/app/api/lib/scoring/getGrade.ts
  web/src/app/api/lib/scoring/getPercentage.ts
  web/src/app/api/lib/scoring/getResultDto.ts
  web/src/app/api/lib/scoring/getScoringResult.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/essay/countEssay.ts
  web/src/app/api/repository/essay/saveEssay.ts
  web/src/app/api/repository/user/createUser.ts
  web/src/app/api/repository/user/findUserByEmail.ts
  web/src/app/api/repository/user/findUserByEmailAndPassword.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/login/route.ts
  web/src/app/api/v1/logout/route.ts
  web/src/app/api/v1/register/[email]/check/route.ts
  web/src/app/api/v1/register/route.ts
  web/src/app/api/v1/verify/idToken/route.ts
Labels: feature

#24 Feat/login pre validation
  web/package-lock.json
  web/package.json
  web/src/app/api/const/dataSet.ts
  web/src/app/api/lib/auth/getDecodedToken.ts
  web/src/app/api/lib/class/ApiError.ts
  web/src/app/api/lib/isLoggedIn.ts
  web/src/app/api/lib/scoring/calculateEssayTotal.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/essay/countEssay.ts
  web/src/app/api/repository/essay/saveEssay.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/login/route.ts
  web/src/app/api/v1/logout/route.ts
  web/src/app/api/v1/register/[email]/check/route.ts
  web/src/app/api/v1/register/route.ts
  web/src/app/api/v1/verify/idToken/route.ts
Labels: feature

#27 feat : main 페이지, result 페이지 수정
  web/package.json
  web/public/fonts/PretendardVariable.woff2
  web/public/images/result_page.png
  web/public/images/robot.png
  web/src/app/(auth)/signin/page.tsx
  web/src/app/(auth)/signup/page.tsx
  web/src/app/_components/Footer.tsx
  web/src/app/_components/Header.tsx
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/app/page.tsx
  web/src/app/result/_components/CategoryGrade.tsx
  web/src/app/result/_components/DetailView.tsx
  web/src/app/result/_components/OverallPercentage.tsx
  web/src/app/result/_components/RadarView.tsx
  web/src/app/result/_components/RecentHistoryView.tsx
  web/src/app/result/_components/ResultSection/DetailView.tsx
  web/src/app/result/_components/ResultSection/OverView.tsx
  web/src/app/result/_components/ResultSection/SummaryView.tsx
  web/src/app/result/_components/ResultSection/index.tsx
  web/src/app/result/_components/ReviewNote.tsx
  web/src/app/result/_components/ReviewSection.tsx
  web/src/app/result/_components/SummaryView.tsx
  web/src/app/result/page.tsx
  web/src/app/writing/_components/EssayLength.tsx
  web/src/app/writing/_components/EssaySection.tsx
  web/src/app/writing/_components/SelectTopic.tsx
  web/src/app/writing/page.tsx
  web/src/components/Footer.tsx
  web/src/components/Note.tsx
  web/src/components/TapBar.tsx
  web/src/components/TopicBar.tsx
  web/src/components/ui/Button.tsx
  web/src/components/ui/Chart/BoxPlot.tsx
  web/src/components/ui/Chart/DoughnutChart.tsx
  web/src/components/ui/Chart/HalfDoughnutChart.tsx
  web/src/components/ui/Chart/HorizontalBarChart.tsx
  web/src/components/ui/Chart/NormalDistributionGraph.tsx
  web/src/components/ui/Chart/RadarChart.tsx
  web/src/components/ui/Chart/TwiceBarChart.tsx
  web/src/components/ui/Chart/index.ts
  web/src/components/ui/Icon/IconOutline.tsx
  web/src/lib/constants/chart.ts
  web/src/lib/constants/colors.ts
  web/src/lib/constants/constants.ts
  web/src/lib/styles/note.module.css
  web/src/lib/types/index.d.ts
  web/src/lib/utils/chart/createNormalDistData.ts
  web/src/lib/utils/colors/index.ts
  web/src/lib/utils/isEmail.ts
  web/src/lib/utils/utils.ts
  web/tailwind.config.js
Labels: feature

#32 Feat/get essay evaluate result
  web/package-lock.json
  web/src/app/api/lib/class/ApiError.ts
  web/src/app/api/lib/makeCreatedAt.ts
  web/src/app/api/lib/scoring/makeEvaluateResponse.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/essay/saveEssay.ts
  web/src/app/api/repository/scoringResult/findScoringResultByEssayId.ts
  web/src/app/api/repository/scoringResult/saveScoringResult.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/history/[email]/history/route.ts
  web/src/app/api/v1/logout/route.ts
Labels: feature

#30 feat : 로그인 API 연결
  web/package-lock.json
  web/package.json
  web/src/app/(auth)/layout.tsx
  web/src/app/(auth)/signin/page.tsx
  web/src/app/(auth)/signup/page.tsx
  web/src/app/_components/StartButton.tsx
  web/src/app/page.tsx
  web/src/app/result/[id]/_components/BoxPlotView.tsx
  web/src/app/result/[id]/_components/CategoryGrade.tsx
  web/src/app/result/[id]/_components/DetailView.tsx
  web/src/app/result/[id]/_components/OverallPercentage.tsx
  web/src/app/result/[id]/_components/RadarView.tsx
  web/src/app/result/[id]/_components/RecentHistoryView.tsx
  web/src/app/result/[id]/_components/ReviewNote.tsx
  web/src/app/result/[id]/_components/ReviewSection.tsx
  web/src/app/result/[id]/_components/SummaryView.tsx
  web/src/app/result/[id]/page.tsx
  web/src/app/result/page.tsx
  web/src/app/test/page.tsx
  web/src/app/writing/_components/IpadNote.tsx
  web/src/components/ui/Chart/BoxPlot.tsx
  web/src/components/ui/Chart/index.ts
  web/src/components/ui/Input.tsx
  web/src/lib/constants/constants.ts
  web/src/store/signupStore.ts
Labels: feature

#36 Feat/reflect changed structure
  web/src/app/api/const/dataSet.ts
  web/src/app/api/lib/scoring/calculateEssaySub.ts
  web/src/app/api/lib/scoring/calculateEssayTotal.ts
  web/src/app/api/lib/scoring/calculateGrade.ts
  web/src/app/api/lib/scoring/makeEvaluateResponse.ts
  web/src/app/api/lib/scoring/makeScoringResult.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/lib/utils/reduceArray.ts
  web/src/app/api/lib/utils/reduceObject.ts
  web/src/app/api/repository/essay/saveEssay.ts
  web/src/app/api/repository/scoringResult/findScoringResultByEssayId.ts
  web/src/app/api/repository/scoringResult/saveScoringResult.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/login/route.ts
  web/src/app/api/v1/logout/route.ts
  web/src/app/api/v1/verify/idToken/route.ts
Labels: feature

#37 feat : result 데이터 바인딩, history 레이아웃
  web/public/images/robot/robot.png
  web/public/word_cloud.png
  web/src/app/(auth)/layout.tsx
  web/src/app/(auth)/signin/page.tsx
  web/src/app/(auth)/signup/page.tsx
  web/src/app/api/repository/scoringResult/findScoringResultByEssayId.ts
  web/src/app/globals.css
  web/src/app/history/_components/RecentGradeHistory.tsx
  web/src/app/history/_components/WordCloud.tsx
  web/src/app/history/_components/WordTable.tsx
  web/src/app/history/page.tsx
  web/src/app/layout.tsx
  web/src/app/page.tsx
  web/src/app/result/[id]/_components/BoxPlotView.tsx
  web/src/app/result/[id]/_components/CategoryGrade.tsx
  web/src/app/result/[id]/_components/DetailView.tsx
  web/src/app/result/[id]/_components/OverallPercentage.tsx
  web/src/app/result/[id]/_components/RadarView.tsx
  web/src/app/result/[id]/_components/RecentHistoryView.tsx
  web/src/app/result/[id]/_components/ResultView.tsx
  web/src/app/result/[id]/_components/ReviewNote.tsx
  web/src/app/result/[id]/_components/ReviewSection.tsx
  web/src/app/result/[id]/_components/SummaryView.tsx
  web/src/app/result/[id]/page.tsx
  web/src/app/test/page.tsx
  web/src/app/writing/_components/IpadNote.tsx
  web/src/app/writing/_components/SelectTopic.tsx
  web/src/components/StoreInitializer.tsx
  web/src/components/ui/Chart/BoxPlot.tsx
  web/src/components/ui/Chart/ComboChart.tsx
  web/src/components/ui/Chart/DoughnutChart.tsx
  web/src/components/ui/Chart/HalfDoughnutChart.tsx
  web/src/components/ui/Chart/LineChart.tsx
  web/src/components/ui/Chart/RadarChart.tsx
  web/src/components/ui/Chart/index.ts
  web/src/lib/constants/fonts.ts
  web/src/lib/hooks/useCheckUser.ts
  web/src/lib/types/index.d.ts
  web/src/lib/utils/api/fetchCheckDuplicateEmail.ts
  web/src/lib/utils/api/fetchLogOut.ts
  web/src/lib/utils/api/fetchLogin.ts
  web/src/lib/utils/api/fetchSignUp.ts
  web/src/lib/utils/api/getUser.ts
  web/src/store/authStore.ts
  web/src/store/essayStore.ts
  web/tailwind.config.js
Labels: feature

#39 Feat/result page history
  web/src/app/api/const/dataSet.ts
  web/src/app/api/const/dummyScore.ts
  web/src/app/api/const/regExp.ts
  web/src/app/api/lib/scoring/makeScoringResult.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/lib/utils/reduceArray.ts
  web/src/app/api/lib/utils/reduceObject.ts
  web/src/app/api/repository/essay/findEssayById.ts
  web/src/app/api/repository/scoringResult/findScoringResultByEssayId.ts
  web/src/app/api/repository/scoringResult/findScoringResultsByUidAndOrderBy.ts
  web/src/app/api/repository/user/createAuth.ts
  web/src/app/api/repository/user/saveUser.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/register/route.ts
Labels: feature

#41 feat : 회원가입 시 성별, 학교명 입력 추가
  web/src/app/(auth)/signup/page.tsx
  web/src/lib/types/index.d.ts
Labels: feature

#42 Feat/history page
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/scoringResult/findScoringResultsByUidAndOrderBy.ts
  web/src/app/api/repository/user/saveUser.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/history/[email]/history/route.ts
  web/src/app/api/v1/history/[email]/route.ts
  web/src/app/api/v1/register/route.ts
Labels: feature

#46 Feat/change data structure
  web/src/app/api/const/dataSet.ts
  web/src/app/api/const/dummyScore.ts
  web/src/app/api/lib/callback/scorePercentageCallback.ts
  web/src/app/api/lib/makeSubScoring.ts
  web/src/app/api/lib/scoring/makeScoringResult.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/essay/findEssayById.ts
  web/src/app/api/repository/essay/findEssayByUidAndOrderBy.ts
  web/src/app/api/repository/essay/saveEssay.ts
  web/src/app/api/repository/scoringResult/findScoringResultByEssayId.ts
  web/src/app/api/repository/scoringResult/findScoringResultsByUidAndOrderBy.ts
  web/src/app/api/repository/scoringResult/saveScoringResult.ts
  web/src/app/api/repository/user/saveUserInfo.ts
  web/src/app/api/repository/userInfo/findUserInfoByEmail.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/history/[email]/route.ts
  web/src/app/api/v1/register/route.ts
  web/src/app/api/v1/user/[email]/route.ts
Labels: feature

#49 fix: history email 검증 로직 제거
  web/src/app/api/v1/history/[email]/route.ts
Labels: bugfix

#50 feat: result 페이지 countTotal 추가, history 페이지 greade 추가.
  web/src/app/api/const/dataSet/expression.ts
  web/src/app/api/const/dataSet/persuade.ts
  web/src/app/api/lib/makeSubScoring.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/history/[email]/route.ts
Labels: feature

#35 Feat/add new scoring model
  python/app.py
Labels: feature

#51 feat: scoringResult 삭제
  web/src/app/api/const/dummyScore.ts
  web/src/app/api/lib/scoring/fetchToScoringServer.ts
  web/src/app/api/repository/essay/findEssayByUidAndOrderBy.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/history/route.ts
Labels: feature

#52 feat: ai 서버 주소 분리, topic에 맞는 id값 설정, topic 마다의 dataSet 저장.
  web/src/app/api/const/dataSet/expression.ts
  web/src/app/api/const/dataSet/persuade.ts
  web/src/app/api/const/dataset.ts
  web/src/app/api/lib/makeSubScoring.ts
  web/src/app/api/lib/scoring/fetchToScoringServer.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/v1/evaluate/[essayId]/result/route.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/history/route.ts
Labels: feature

#54 feat: wordCloud 추가
  web/src/app/api/const/dummyScore.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/repository/wordCloud/findWordCloudByUid.ts
  web/src/app/api/repository/wordCloud/saveWordCloud.ts
  web/src/app/api/v1/evaluate/route.ts
  web/src/app/api/v1/history/route.ts
Labels: feature

#56 feat : 최종 수정 및 responsive 작업 중
  python/alternative/app.py
  python/explain/app.py
  web/public/images/result_page.png
  web/public/images/robot/robot.png
  web/src/app/(dashboard)/_components/HistoryView.tsx
  web/src/app/(dashboard)/history/_components/CategoryRadar.tsx
  web/src/app/(dashboard)/history/_components/RecentGradeHistory.tsx
  web/src/app/(dashboard)/history/_components/WordCloud.tsx
  web/src/app/(dashboard)/history/_components/WordTable.tsx
  web/src/app/(dashboard)/history/page.tsx
  web/src/app/(dashboard)/result/[id]/_components/BoxPlotView.tsx
  web/src/app/(dashboard)/result/[id]/_components/CategoryGrade.tsx
  web/src/app/(dashboard)/result/[id]/_components/CategoryList.tsx
  web/src/app/(dashboard)/result/[id]/_components/DetailsView.tsx
  web/src/app/(dashboard)/result/[id]/_components/OverallPercentage.tsx
  web/src/app/(dashboard)/result/[id]/_components/Progress.tsx
  web/src/app/(dashboard)/result/[id]/_components/RadarView.tsx
  web/src/app/(dashboard)/result/[id]/_components/Summary.tsx
  web/src/app/(dashboard)/result/[id]/page.tsx
  web/src/app/globals.css
  web/src/app/page.tsx
  web/src/components/TypeTag.tsx
  web/src/components/ui/Chart/LineChart.tsx
  web/src/components/ui/Chart/RadarChart.tsx
  web/src/lib/utils/api/essay/fetchResult.ts
  web/src/lib/utils/chart/plugin/textCenterPlugin.ts
Labels: feature

#57 feat: ai server 구조 변경에 따른 fetch 로직 변경
  web/src/app/api/const/dummyScore.ts
  web/src/app/api/const/topicIdMap.ts
  web/src/app/api/const/topicIdServerMap.ts
  web/src/app/api/lib/scoring/fetchToScoringServer.ts
  web/src/app/api/lib/types.d.ts
  web/src/app/api/lib/wordCloud/fetchToWordCloudServer.ts
  web/src/app/api/v1/evaluate/route.ts
Labels: feature

#58 feat : 반응형 작업 완료
  python/essay/app.py
  python/preprocess.ipynb
  python/preprocess_data/본인의 성격_train.xlsx
  python/preprocess_data/본인의 성격_val.xlsx
  web/public/images/robot/robot.png
  web/src/app/(auth)/layout.tsx
  web/src/app/(auth)/signin/page.tsx
  web/src/app/(dashboard)/_components/HistoryView.tsx
  web/src/app/(dashboard)/history/_components/CategoryRadar.tsx
  web/src/app/(dashboard)/history/_components/RecentGradeHistory.tsx
  web/src/app/(dashboard)/history/_components/WordCloud.tsx
  web/src/app/(dashboard)/history/_components/WordTable.tsx
  web/src/app/(dashboard)/history/page.tsx
  web/src/app/(dashboard)/layout.tsx
  web/src/app/(dashboard)/result/[id]/_components/BoxPlotView.tsx
  web/src/app/(dashboard)/result/[id]/_components/CategoryGrade.tsx
  web/src/app/(dashboard)/result/[id]/_components/DetailsView.tsx
  web/src/app/(dashboard)/result/[id]/_components/OverallPercentage.tsx
  web/src/app/(dashboard)/result/[id]/_components/Progress.tsx
  web/src/app/(dashboard)/result/[id]/_components/RadarView.tsx
  web/src/app/(dashboard)/result/[id]/_components/ReviewNote.tsx
  web/src/app/(dashboard)/result/[id]/_components/Summary.tsx
  web/src/app/(dashboard)/result/[id]/page.tsx
  web/src/app/_components/Header.tsx
  web/src/app/globals.css
  web/src/app/page.tsx
  web/src/app/writing/_components/IpadNote.tsx
  web/src/app/writing/page.tsx
  web/src/components/StoreInitializer.tsx
  web/src/components/TypeTag.tsx
  web/src/components/ui/Button.tsx
  web/src/components/ui/Chart/LineChart.tsx
  web/src/lib/constants/api.ts
  web/src/lib/constants/regExp.ts
  web/src/lib/constants/topic.ts
  web/src/lib/hooks/useOnClickOutside.ts
  web/src/lib/types/index.d.ts
  web/src/lib/utils/api/auth/fetchCheckDuplicateEmail.ts
  web/src/lib/utils/api/auth/fetchSignIn.ts
  web/src/lib/utils/api/auth/fetchSignOut.ts
  web/src/lib/utils/api/auth/fetchSignUp.ts
  web/src/lib/utils/api/essay/fetchEvaluateEssay.ts
  web/src/lib/utils/api/essay/fetchResult.ts
  web/src/lib/utils/api/getUser.ts
  web/src/lib/utils/api/history/fetchHistory.ts
  web/src/lib/utils/chart/plugin/textCenterPlugin.ts
  web/src/lib/utils/isEmail.ts
  web/tailwind.config.js
Labels: feature
